### ISSUE TITLE
add includes

### ISSUE THREAD

**Issue by tjmehta** [tjmehta/101#109]
```js
includes([1,2,3,4], 1) // true
var notIn = not(includes);
[1,2,3,4,5].filter(notIn([1,2,3])) // [4,5]
```

**Comment by tjmehta** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by bkendall** [comment]
Interesting. Definitely something I would find useful, but how is it functionally different than `!!find(arr, hasProps)` or using `!!find(arr, equals)`? Would this just be a nice wrapper around that?

**Comment by tjmehta** [comment]
it is equivalent to `!find(arr, equals)` but not `!find(arr, hasProps)`

but you avoid an additional lambda

```js
[1,2,3,4,5].filter(notIn([1,2,3])) // [4,5]
// versus
[1,2,3,4,5].filter(function (val) {
  return !find(arr, equals(val));
}) // [4,5]
```
