### ISSUE TITLE
Request: get()

### ISSUE THREAD

**Issue by rstacruz** [tjmehta/101#139]
It would be nice to have a `get()` as a foil to `put()`.

```js
const conf = {
  services: {
    slack: { url: 'http://slack.com' }
  }
}

get(conf, ['services', 'slack', 'url']) //=> 'http://slack.com'
get(conf, ['services', 'twitter', 'url']) //=> undefined
```

**Comment by tjmehta** [comment]
Agreed! Do you prefer keypaths as arrays? 101 uses npmrepo.com/keypather to breakdown string keypaths

Typed using my thumbs..

**Comment by tjmehta** [comment]
Just realized get functionality is available as '101/pluck'

**Comment by rstacruz** [comment]
Oh. Oops! Nice one

**Comment by tjmehta** [comment]
May need to add a note in docs about this. But closing this issue
