### ISSUE TITLE
del() vs omit()

### ISSUE THREAD

**Issue by rstacruz** [tjmehta/101#146]
It seems they're functionally equivalent. Am I missing something? It might be worth documenting how they're different :)

**Comment by tjmehta** [comment]
This is why I want to rename immutable helpers to be exactly what they are.

Omit is immutable-delete :)

**Comment by rstacruz** [comment]
Lol. Holy crap, had no idea del was mutable. BRB fixing bugs I didn't know
about

**Comment by rstacruz** [comment]
For the record, what mutable functions are there in 101?

**Comment by rstacruz** [comment]
Also, if immutable is the norm in 101, it might be better to mark the
mutable ones instead.

**Comment by tjmehta** [comment]
put, omit, and technically pluck (unless plucking to an object, which would not be a copy of that object)

**Comment by tjmehta** [comment]
put and omit are labelled as immutable. Definitely why I want to create an index in the readme and rename things. I've been waiting for a major update to do this. Thinking about what do w/ es6 methods would be good to avoid double major bumps in close proximity (that or deprecate via warning.. not sure yet).

**Comment by tjmehta** [comment]
created a "2.0.0" issue to discuss the mutable/immutable issue and "index" issue to discuss documentation updates. Closing this.
