### ISSUE TITLE
Consider building as ES6 modules.

### ISSUE THREAD

**Issue by tomekwi** [tjmehta/101#38]
##### Why

You've reached a conclusion in #17, that AMD is fairly compatible with CommonJS – you can use one within the other or transpile one to the other. That's not the case with ES6 modules. They are designed to be statically analysable (without executing the code) – so there are things impossible to transpile. Such as:

```js
if (hasToGo) require('car').driveHome();
// ...or:
module.exports = something || somethingElse;
```

##### How

Looking by the simplicity of your modules, it should be easy to copy each file to `101/es6/`, replacing:
- `module.exports = a;` with    `export default a;`, and
- `var b = require('./b');` with    `import b from './b';`.

I've had a very rough go at this, because I needed two modules in an ES6 project. A simple search-and-replace did it in my case: [tomekwi/101-es6](https://github.com/tomekwi/101-es6).

##### The only problem

The problem is dependency on CommonJS modules (_clone_, _keypather_ and _deep-eql_ –  we should be able to replace _extend_ with 101/assign).

Possible solutions:
1. Implement these ourselves (I guess it can be out of the question at the moment)
2. Compile only non-dependent modules to ES6
3. Compile everything as-it-is (just `import clone from 'clone';`). Some compilers ([6to5](//6to5.org/)) can handle this as a temporary ES5-ES6 brigde.

**Comment by stoeffel** [comment]
I would close this in favour of #42. I think a complete move to es6 using 6to5 or traceur would be cleaner.

**Comment by tjmehta** [comment]
I am punting on this for now. I know ES6 traction is picking up fast. Let's revisit this idea after a few months. Long answer here: https://github.com/tjmehta/101/pull/62

**Comment by stoeffel** [comment]
> Let's revisit this idea after a few months

Sure will do :smile_cat:
