### ISSUE TITLE
Consider authoring in ES6

### ISSUE THREAD

**Issue by tomekwi** [tjmehta/101#42]
It's another idea than #38. Author in ES6, transpile to a universal module format for node, AMD and the browser.

[The original idea came from Ryan Florence some time ago](http://ryanflorence.com/2013/es6-modules-and-browser-app-delivery/). I've followed his advice in [tomekwi/as.js](https://github.com/tomekwi/as.js). The technology is still quite rough, but everything seems work smoothly.

**Comment by tjmehta** [comment]
Cool, thanks I will check this iut

—@tjmehta
Typed using my thumbs..

**Comment by tomekwi** [comment]
One more thought. Reading that
> 101 will be maintained to [... match] a widely supported JS version

– maybe we could branch out an experimental 2.0.x branch, tailored to ES6? Without the cruft which already comes bundled in ES6 (like `find` or `assign`)?

This could be used as it is in ES6 projects, and optionally compiled to ES5. [6to5](http://6to5.org) does a great job with that.

If you're interested, you can have a look at [tomekwi/mithril-n](https://github.com/tomekwi/mithril-n) – I've managed to polish my ES6 workflow for testing and compilation.

**Comment by tjmehta** [comment]
I am still unsure about all this ES6 stuff. It seems you guys have a lot more experience that me about all the options. When you two (@tomekwi, @stoeffel) have been using using es6 I am assuming you are probably transpiling your code (for browser usage) or using node with flags.

In both of these cases, how are you importing other npm modules?

**Comment by stoeffel** [comment]
I'm often using 6to5(now babel) with a pretty straightforward workflow.
I have a `.es6` next to the transpiled `.js` file. Checkout https://github.com/stoeffel/chickencurry as an example. But we could have a es6 folder with the files we are working on and transpile them into the root of the project and add the es6 folder to npmignore.

> how are you importing other npm modules? 

You can reguire modules like this `import foo from 'foo';`. Checkout https://github.com/stoeffel/partition-all/blob/master/index.es6#L3

I can create a simple proposal if you like?

**Comment by tjmehta** [comment]
I just saw what you proposed in #62. Make sense, but I think you may have misunderstood my question.
Let me try to be more clear with what I am asking. 

My main question is:
When developing an ES6 module/application is it difficult to use CommonJS modules?

I don't think I'd want to start implementing 101 in ES6 until it is widely supported (and wouldn't require transpiling to ES5). Reasons include: mainstream readability, easier for contributors, avoid transpiling, avoid doubling size of source, etc. Thoughts?

**Comment by stoeffel** [comment]
> When developing an ES6 module/application is it difficult to import CommonJS modules

No you just import it.

> I don't think I'd want to start implementing 101 in ES6 until it is widely supported

I think then we shouldn't move to es6. But I think there is no down side to transpiling, a lot of libraries are doing it and developers are getting more and more used to it. IMHO es6 code is often easier to read. If we add a CONTRIBUTING.md contributors know where they should change things.

> doubling size of source

es6 files can be excluded from npm.

**Comment by tomekwi** [comment]
> how are you importing other npm modules?

@tjmehta, what @stoeffel says is true when working with babel. All ES6 modules are simply transpiled and run as ES5 – whether in node or in the browser (via webpack or browserify). So `import foo from "foo"` becomes `var foo = require("foo")`.

But, as a matter of fact, ES6 specs say nothing about supporting CommonJS or AMD.

However: when an implementation of modules comes to node, I'm 100% sure they'll work out of the box with CJS – otherwise the whole ecosystem of npm would become useless. For browsers we'll need some kind of a workaround to marry modules and CJS – but today we need workarounds for that just as well.

Working with babel is pure pleasure :) But I must admit I had a hard time in a project compiled with [traceur](https://github.com/google/traceur-compiler). In order to use 101 I had to fork, "transpile" all function and watch out not to use those which pull in CommonJS modules.

So I think an ES6 version would already improve accessibility.

And after all, it's a step which will need to be taken sooner or later :)

**Comment by tomekwi** [comment]
> I don't think I'd want to start implementing 101 in ES6 until it is widely supported

Working with babel is pure pleasure :) But I must admit I had a hard time in a project compiled with [traceur](https://github.com/google/traceur-compiler). In order to use 101 I had to fork, "transpile" all function and watch out not to use those which pull in CommonJS modules.

So I think an ES6 version would already improve accessibility.

And after all, it's a step which will need to be taken sooner or later :)

**Comment by tomekwi** [comment]
> es6 files can be excluded from npm

I'm not sure I'd do that @stoeffel. There are people who'll want to pull the ES6 version directly – for example to avoid doubling some of babel's runtime code in a webpacked package.

**Comment by stoeffel** [comment]
> There are people who'll want to pull the ES6 version directly – for example to avoid doubling some of babel's runtime code in webpacked code.

Okay, didn't know that. Thx

**Comment by stoeffel** [comment]
> Working with babel is pure pleasure :)

:100: :+1:

**Comment by stoeffel** [comment]
@tjmehta I guess you have to decide if you want to switch or not. Clearly @tomekwi and I are pro ES6 :smile: 
How about you pull #62 into a `es6` branch and tinker a bit on your own to get a feeling if you like it or not?

**Comment by tjmehta** [comment]
I am punting on this for now. I know ES6 traction is picking up fast. Let's revisit this idea after a few months. Long answer here: https://github.com/tjmehta/101/pull/62

**Comment by tjmehta** [comment]
Reopening this for discussion.
Circumstances have changed with node4 supporting many ES6 features.
Keep in mind, browser support for ES6 is still quite fragmented. 
Any ideas on how we can transition to support ES6 features?

**Comment by bkendall** [comment]
Babel?

On Tue, Nov 10, 2015 at 9:36 PM, Tejesh Mehta <notifications@github.com>
wrote:

> Reopened #42 <https://github.com/tjmehta/101/issues/42>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tjmehta/101/issues/42#event-460959746>.
>



-- 
-----------
Bryan Kendall

**Comment by cflynn07** [comment]
@tjmehta using babel presets, such as `es2015` should make it easier to write features in ES6. Anything you write in ES6 would be transformed to browser compliant JS. As browsers add support for ES6 features, new presets will be created. You can swap which preset you use with babel to get the latest ES6 supported features.

http://babeljs.io/docs/plugins/preset-es2015/

**Comment by tjmehta** [comment]
I am thinking about making a breaking change to 101 in early 2016 to assume es6 as the widely supported JavaScript.

Optimally I would like to support es5 and es6, but only use transpiled code for es5 environments.

Typed using my thumbs..

**Comment by tjmehta** [comment]
moving es6 convo to #150
