### ISSUE TITLE
npm test should use local ./node_modules instead of assuming global

### ISSUE THREAD

**Issue by jrf0110** [tjmehta/101#45]
```javascript
"test": "./node_modules/.bin/lab -c test"
```

That way one can simply `npm install` to run the tests

**Comment by tjmehta** [comment]
Npm scripts can read binaries from node_modules, did you see it not working?

**Comment by jrf0110** [comment]
ahh I didn't realize that - I tried it out previously, but must have unknowingly derped the command somehow and misattributed the cause!
