### ISSUE TITLE
or doesn't return boolean

### ISSUE THREAD

**Issue by stoeffel** [tjmehta/101#52]
As the jsdoc of `or` states, `or` should return a boolean.
```js
/**
 * Functional version of ||
 * @function module:101/and
 * @param {*} a - any value
 * @param {*} b - any value
 * @return {boolean} a || b
 */
```
But it returns the value passed to the function, if it is thruthy.
```js
var or = require('./or');
or(1, false);
// => 1
or("101", false);
// => "101"
```

I have a PR ready if you want to change this behaviour.

**Comment by tomekwi** [comment]
Maybe it just mimics the `||`?

```js
1 || false
// » 1
"101" || false
// » "101"
```

**Comment by tomekwi** [comment]
Then we should change the docs to
```
 * @return {*} a || b
```

**Comment by tjmehta** [comment]
@stoeffel the jsdoc is wrong, but the behavior is correct. It functions like the `||` operator.

**Comment by stoeffel** [comment]
@tjmehta Okay, I will create a PR to fix the jsdoc.
