### ISSUE TITLE
`set` doesn't support keypaths

### ISSUE THREAD

**Issue by tomekwi** [tjmehta/101#54]
As of 101@0.9.0:

```js
set({a: {b: "c"}}
  , "a.b", "d"
  );
// » {a: {b: "c"}, "a.b": "d"}
```

Maybe that's intended – but [the docs](https://github.com/tjmehta/101#set) say:
>     // supports keypaths by default

**Comment by tjmehta** [comment]
Nice we'll have to make this use keypather.

**Comment by tomekwi** [comment]
I've created a PR for this in #63
