### ISSUE TITLE
composed function takes only one argument

### ISSUE THREAD

**Issue by stoeffel** [tjmehta/101#58]
Currently a composed function takes only one argument:

```js
function compose(f,g) {
  return function composed(x) { 
    return f(g(x));
  } 
```

With this implementation you can't do this:
```js
var add = function(a, b) { return a+b; };
var sqr = function(a) { return a*a; };

var composed = compose(sqr, add);
composed(1, 2);
// expected => 9
// actual => NaN
```

How about we change compose to create a function which passes all arguments to the first function:

```js
function compose(f,g) {
  return function composed(/* args */) { 
    var args = Array.prototype.slice.call(arguments);

    return f(g.apply(null, args));
  } 
```

Checkout my implementation of `compose` it passes all arguments to the first function (https://github.com/stoeffel/compose-function)

**Comment by tjmehta** [comment]
I'd accept a PR for this ( passing all arguments to the first function )

**Comment by stoeffel** [comment]
> I'd accept a PR for this ( passing all arguments to the first function )

done :smile:
