### ISSUE TITLE
`set` modifies the original object

### ISSUE THREAD

**Issue by tomekwi** [tjmehta/101#64]
The [readme for `set`](https://github.com/tjmehta/101#set) says:

> returns a new obj with the key and value set

I'd seen it as a powerful functionality which allowed me to get immutability in JS without using [an obese library][i].
[i]: https://www.npmjs.com/package/immutable "Immutable"

– until I noticed that [it's the original object that gets changed and returned](https://github.com/tjmehta/101/blob/master/set.js#L37) after all.

Is it supposed to be so?

**Comment by tomekwi** [comment]
A PR is ready if you'd like to change the current behaviour.

I know it can break backwards-compatibility – so it might be better to first release it with 1.0.0. @tjmehta, @stoeffel – what do you think?

**Comment by stoeffel** [comment]
I will review it later. I'm afk.

Tomek Wiszniewski <notifications@github.com> schrieb am Di., 17. Feb. 2015
12:44:

**Comment by tomekwi** [comment]
Anyway, if we don't change the behaviour, we need to change the docs. It costed me about 3 hours of bugfixing in my project :)

**Comment by stoeffel** [comment]
I'm :+1: on changing the current behaviour. PR looks good to me.
