### ISSUE TITLE
groupBy

### ISSUE THREAD

**Issue by tjmehta** [tjmehta/101#74]
Should it work with reduce?
```js
[ 
  { foo: 'bar', bar: 'yo' }, 
  { foo: 'bar' }, 
  { foo: 'flux' }, 
  { foo: 'flux', qux: 100 }
].reduce(groupBy('foo'), {});
/* returns 
{
  'bar': [
    { foo: 'bar', bar: 'yo' },
    { foo: 'bar' }
  ],
  'flux': [
    { foo: 'flux' }, 
    { foo: 'flux', qux: 100 }
  ]
}
*/
```
Note: It requires an initial value which makes it a less "plug and play".

Or just 

```js
groupBy(arr, 'foo')
```

**Comment by tjmehta** [comment]
@stoeffel @tomekwi @bkendall @podviaznikov thoughts?

**Comment by podviaznikov** [comment]
I like `groupBy(arr, 'foo')`. It just shorter (minus `.reduce` and `{}`).
Akso I personally like functions that accept everything they need as parameters.

**Comment by tjmehta** [comment]
ooh maybe it should take a function:
```js
reduce(groupBy(pluck('foo')), {})
// or
groupBy(arr, pluck('foo'))
```

**Comment by stoeffel** [comment]
+1 for taking a function.

**Comment by tjmehta** [comment]
do these helpers belong in 101?

**Comment by tomekwi** [comment]
@podviaznikov I like the reduce variant, because it's easier to understand.

`groupBy` and `indexBy` are quite high-level functions anyway. But I guess these are things we often need, and end up writing over and over again. So good fit for a swiss army knife such as 101.

**Comment by tjmehta** [comment]
The initial value can be avoided it we accept that `[ ].reduce(groupBy('foo'));` will throw an error.

**Comment by tomekwi** [comment]
No initial value generally behaves in a cunning unexpected way:

```js
[ 
  { foo: 'bar', bar: 'yo' }, 
].reduce(groupBy('foo'));
/* returns 
{ foo: 'bar', bar: 'yo' }
*/

[ 
  { foo: 'bar', bar: 'yo' }, 
  { foo: 'bar' }
].reduce(groupBy('foo'));
/* returns 
{
  foo: 'bar',
  bar: [
    { foo: 'bar' }
  ]
}
*/
```

**Comment by tjmehta** [comment]
@tomekwi you can have a special case for index 0

[].reduce(function (a, b, index, arr) {});

**Comment by tomekwi** [comment]
Yeah, good idea. But I wonder what developers would expect of `[{}, {a: 1}, {a: 2}].reduce(groupBy('a'))` though – knowing how reduce works. Myself, I guess I'd pass the second argument to make it explicit anyway.

And you can't override this – can you:
```js
[ 
  { foo: 'bar', bar: 'yo' }, 
].reduce(groupBy('foo'));
/* returns 
{ foo: 'bar', bar: 'yo' }
*/
```

**Comment by tjmehta** [comment]
added a while ago..	
101@1.6.0
