### ISSUE TITLE
tail

### ISSUE THREAD

**Issue by stoeffel** [tjmehta/101#88]
With #87 101 will have a `first` function which often comes with a `tail` function.

```js
tail([1, 2, 3, 4]);
// => [2, 3, 4]

tail('_hello');
// => 'hello'
```

:sunflower:

**Comment by tjmehta** [comment]
This should be able to be accomplished very easily by slice. `stringOrArr.slice(1)`

**Comment by stoeffel** [comment]
But it's usefull with `compose`.

**Comment by tjmehta** [comment]
I see, I thought that may be the purpose. I have been thinking about a solution in another context that may solve your problem. What I have come up with so far is that 101 may need an `invoke` util.

Example usage:
```javascript
var compose = require('101/compose');
var invoke = require('101/invoke');
var splitArgs = ['.'];
var joinArgs = [' '];
var str = 'hello.world';
var replacePeriodsWithSpaces = compose(invoke('join', joinArgs), invoke('split', splitArgs));

replacePeriodsWithSpaces(str); // 'hello world'
// Note: This may be a bad example because Strings have a replace method, 
// but it is a good example of invoke's usage
```

I have been thinking about adding this type of functionality to pluck (as keypather supports function invocation). Keypather's api for function invocation is good for methods that have arguments, but gets a bit messy when the do. I have some other ideas about how we improve that. First, I want to know if this solves your problem.

**Comment by stoeffel** [comment]
> What I have come up with so far is that 101 may need an invoke util.

+1.

Will think about this more next week have to go to bed :smile:

**Comment by stoeffel** [comment]
I like the idea of invoke. But I still think that tail (and first) are so essential to fp that they deserve to be a own function. And we have other small functions like `and` and `or` and they too are useful functions.
