### ISSUE TITLE
proposal: bindAll

### ISSUE THREAD

**Issue by albertorestifo** [tjmehta/101#91]
Yes, yes, the native `Function.prototype.bind` method is solid, but there are situations where the Underscore `bindAll` method is just what you need.

I propose to extract the bindAll method from the Underscore library, remove the support for when the ES5 `bind` is not available and call it a day.

If there is enough interest, I can create a PR

**Comment by tjmehta** [comment]
@albertorestifo I really love `bindAll` I use it in a ton of projects when class instances have event handlers that need to be added and eventually removed.

This would be the first function that is tuned for a specific use case (IMO it is similar to `indexBy` and `groupBy` which have yet to be added).

@bkendall @podvianikov @stoeffel what are your thoughts about adding util methods like these to 101?

**Comment by stoeffel** [comment]
SGTM. It is a function I see myself using a lot too.

**Comment by albertorestifo** [comment]
Ok, I will make a PR. Just one thing, do we want the LoDash or Underscore one?

The only difference is that LoDash can bind to every method in the object if you don't specify them. I feel this will make easier to create abuses.

**Comment by tjmehta** [comment]
IMO It should bind all keys that are functions and you can provide a filter optionally by array of key names or if you think users want more flexibility accept a function that can act as a filter



—@tjmehta
Typed using my thumbs..

**Comment by albertorestifo** [comment]
I'm working on a Pull Request

**Comment by albertorestifo** [comment]
I encountered a problem:

Getting the array of keys of an `Object.prototype` is not as straight-forward as I expected. I would need to do so in order to implement the `bindAll` call without any method specified.

Lodash solution can be seen here: https://github.com/lodash/lodash/blob/master/lodash.js#L9538

Should I also add a `keys` module?
