### ISSUE TITLE
Publishing functions as single modules

### ISSUE THREAD

**Issue by stoeffel** [tjmehta/101#92]
First, I know this is against one of the philosophies of 101. But as the library grows it would sometimes be nice if one could install only what he needs. i.e `npm i 101-curry`. We could create a cli-tool to publish only changed function and keep developing 101 in one repo.
What are your thoughts on this?

**Comment by tjmehta** [comment]
I think 101 is an acceptable size at the moment, but let's definitely revisit this topic in the future.
